---
  - name: Install bash and completion
    homebrew:
      name: [
        'bash',
        'bash-completion@2'
      ]
      state: present

  - name: Add bash path to /private/etc/shells
    lineinfile:
      dest: /private/etc/shells
      line: '/usr/local/bin/bash'
    become: yes
