---
- hosts: localhost
  gather_facts: yes

  roles:
    - installation
    - configuration
    - name: asdf
      vars:
        plugins:
          - {name: "terraform"}
          - {name: "terraform-docs"}
          - {name: "tflint"}
