---
- name: Link global configs
  ansible.builtin.file:
    src: "~/.dotfiles/symlinks/{{ item }}"
    dest: "~/.{{ item }}"
    state: link
  with_items:
    - gitconfig
    - gitignore
    - nanorc
    - zshrc

- name: Link dotfiles
  ansible.builtin.file:
    src: "~/.dotfiles/symlinks/{{ item }}"
    dest: "~/.{{ item }}.dot"
    state: link
  with_items:
    - aliases
