---
  - name: Link dotfiles
    file:
      src: "~/.dotfiles/symlinks/{{ item }}"
      dest: "~/.{{ item }}"
      state: link
    with_items:
      - aliases
      - gitconfig
      - gitignore
      - nanorc
      - zshrc

  - name: Link system files from dropbox
    file:
      src: "~/Dropbox/system/dotfiles/symlinks/{{ item }}"
      dest: "~/.{{ item }}"
      state: link
    with_items:
      - hosts
    when: dropbox_synced_stat.stat.exists is defined and dropbox_synced_stat.stat.exists == True
