---
  - name: Install VSCode plugins
    command: "/usr/local/bin/code --install-extension {{ item }}"
    with_items:
      - alefragnani.project-manager
      - bajdzis.vscode-database
      - batisteo.vscode-django
      - bbenoist.vagrant
      - castwide.solargraph
      - chef-software.chef
      - christian-kohler.path-intellisense
      - Compilenix.vscode-zonefile
      - coolbear.systemd-unit-file
      - d4nyll.devops-extension-pack
      - dakara.transformer
      - DavidAnson.vscode-markdownlint
      - dbaeumer.vscode-eslint
      - dhoeric.ansible-vault
      - donjayamanne.python-extension-pack
      - DotJoshJohnson.xml
      - eamodio.gitlens
      - eriklynd.json-tools
      - evan-buss.font-switcher
      - foxundermoon.shell-format
      - GitHub.vscode-pull-request-github
      - GrapeCity.gc-excelviewer
      - IBM.output-colorizer
      - ipedrazas.kubernetes-snippets
      - ivory-lab.jenkinsfile-support
      - joaomoreno.github-sharp-theme
      - karunamurti.haml
      - magicstack.MagicPython
      - marcostazi.VS-code-vagrantfile
      - misogi.ruby-rubocop
      - ms-azuretools.vscode-docker
      - ms-python.python
      - ms-vscode.sublime-keybindings
      - PKief.material-icon-theme
      - qezhu.gitlink
      - RandomChance.logstash
      - raynigon.nginx-formatter
      - rebornix.ruby
      - redhat.vscode-yaml
      - rupisaini.vscode-ansible-linter
      - secanis.jenkinsfile-support
      - thenikso.github-plus-theme
      - timonwong.shellcheck
      - VisualStudioExptTeam.vscodeintellicode
      - vscoss.vscode-ansible
      - wholroyd.HCL
      - wholroyd.jinja
      - william-voyek.vscode-nginx
      - wingrunr21.vscode-ruby

  - name: Remove user settings
    file:
      path: "~/Library/Application Support/Code/User/settings.json"
      state: absent

  - name: Link settings.json
    file:
      src: "~/.dotfiles/symlinks/vscode_settings.json"
      dest: "~/Library/Application Support/Code/User/settings.json"
      state: link
