---
  - name: Load moom configuration
    command: "defaults import com.manytricks.Moom.plist ~/Dropbox/system/moom/com.manytricks.Moom.plist"
    when: dropbox_synced_stat.stat.exists is defined and dropbox_synced_stat.stat.exists == True
