---
  - name: Install VSCode plugins
    command: "/usr/local/bin/code --install-extension {{ item }}"
    with_items:
      - alefragnani.project-manager
      - bajdzis.vscode-database
      - castwide.solargraph
      - christian-kohler.path-intellisense
      - dbaeumer.vscode-eslint
      - DotJoshJohnson.xml
      - eamodio.gitlens
      - Equinusocio.vsc-material-theme
      - foxundermoon.shell-format
      - GitHub.vscode-pull-request-github
      - GrapeCity.gc-excelviewer
      - karunamurti.haml
      - misogi.ruby-rubocop
      - ms-python.python
      - ms-vscode.sublime-keybindings
      - PKief.material-icon-theme
      - rebornix.ruby
      - robinbentley.sass-indented
      - techer.open-in-browser
      - thenikso.github-plus-theme
      - waderyan.gitblame
