---
  - name: Install from appstore
    shell: mas install {{ item }}
    with_items:
      - 406056744 # Evernote
      - 410628904 # Wunderlist
      - 419330170 # Moom
      - 425424353 # The Unarchiver
      - 524373870 # Due
      - 639968404 # Parcel
      - 880001334 # Reeder
      - 986304488 # Kiwi for gmail
      - 1039633667 # Irvue
      - 1384080005 # Tweetbot
