---
  - name: Install brew packages
    homebrew:
      state: present
      name:
        - antigen
        - asdf
        - autojump
        - awscli
        - bash
        - dialog
        - git
        - gpg
        - grv
        - htop
        - icdiff
        - jq
        - launchctl-completion
        - mas
        - mobile-shell
        - mtr
        - nano
        - ncdu
        - node
        - packer
        - pipenv
        - pngquant
        - python
        - rbenv
        - ruby-build
        - starship
        - telnet
        - tmux-xpanes
        - trash
        - tree
        - watch
        - wget
        - zsh
        - zsh-completions
        - zsh-syntax-highlighting
