---
- name: Install brew packages
  community.general.homebrew:
    state: present
    notify:
      - Cleanup packages
    name:
      - asdf
      - autojump
      - awscli
      - awslogs
      - bash
      - dialog
      - git
      - gpg
      - gh
      - go
      - htop
      - icdiff
      - java
      - jq
      - mas
      - nano
      - ncdu
      - node
      - python@3.9
      - starship
      - telnet
      - tldr
      - watch
      - wget
      - zsh-completions
