---
- name: Brew tap
  community.general.homebrew_tap:
    state: present
    name:
      - homebrew/cask-drivers
      - homebrew/cask-fonts

- name: Install from cask
  ignore_errors: yes
  community.general.homebrew:
    state: present
    notify:
      - Cleanup packages
    name:
      - 1password
      - 1password-cli
      - adobe-creative-cloud
      - alfred
      - android-platform-tools
      - cleanapp
      - discord
      - docker
      - fellow
      - firefox
      - font-fira-code
      - iterm2
      - logitech-options
      - notion
      - openvpn-connect
      - signal
      - slack
      - slite
      - spotify
      - ticktick
      - typora
      - visual-studio-code
      - zoom
