---
- hosts: all
  gather_facts: yes

  pre_tasks:
    - homebrew_tap: tap={{ item }} state=present
      with_items:
        - homebrew/versions
        - homebrew/dupes
        - homebrew/binary
        - homebrew/completions

  tasks:
    - homebrew: name={{ item }} state=present
      with_items:
        - bash
        - bash-completion2
        - node
        - git
        - git-extras
        - git-number
        - rbenv
        - ruby-build
        - htop-osx
        - nano
        - ctags
        - csshx
        - chromedriver
        - packer
        - packer-completion
        - vagrant-completion
        - selenium-server-standalone
        - tree
        - watch
        - wget
        - autojump
        - coreutils
        - icdiff
        - mtr
        - multitail
        - ncdu
        - tmux
        - tmux-cssh

    - npm: name={{ item }} global=yes
      with_items:
        - bower
        - git-stats
        - git-stats-importer@
        - npm
        - jshint
        - tldr

  post_tasks:
    - file: src=~/Dropbox/system/dotfiles/symlinks/{{ item }} dest=~/.{{ item }} state=link
      with_items:
        - hosts
        - ssh

    - file: src=~/.dotfiles/darwin/symlinks/{{ item }} dest=~/.{{ item }} state=link
      with_items:
        - aliases
        - bash_profile

    - file: src=~/.dotfiles/symlinks/{{ item }} dest=~/.{{ item }} state=link
      with_items:
        - bash_prompt
        - functions
        - gitconfig
        - gitignore
        - jshintrc
        - nanorc
        - pylintrc

    - file: src=~/Dropbox/system/Library/{{ item }} dest=~/Library/Application\ Support/{{ item }} state=link
      with_items:
        - Adium\ 2.0
        - Alfred\ 2
