HISTSIZE=100000
SAVEHIST=100000
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_verify
setopt share_history
setopt inc_append_history

eval "$(starship init zsh)"

export EDITOR=nano
export GIT_EDITOR=nano
export GPG_TTY=$(tty)
# export GOPATH=$(go env GOPATH)

if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

  autoload -Uz compinit
  compinit
fi

path=('/usr/local/sbin' '/Users/rafal.malinowski/.dotfiles/bin' $path)
source /usr/local/opt/asdf/asdf.sh

for file in ~/.*.dot; do
  source $file
done

[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/share/autojump/autojump.zsh

export ANSIBLE_SSH_PRIVATE_KEY_FILE=~/.ssh/ec2_instance_connect_key
