---
- hosts: blog-ovh
  gather_facts: yes
  sudo: yes

  pre_tasks:
    - apt: update_cache=yes
    - apt: upgrade=dist

  tasks:
    - apt: name={{ item }} state=present
      sudo: yes
      with_items:
        - bash-completion
        - nodejs
        - git
        - htop
        - alpine-pico
        - tree
        - watch
        - wget
        - curl
        - autojump
        - mtr
        - multitail
        - irssi
        - oidentd

  roles:
    - nginx

  post_tasks:
    - file: path=~/.{{ item }} state=absent
      with_items:
        - aliases
        - bashrc
        - bash_prompt
        - nanorc
        - gitconfig
      sudo: no

    - file: src=~/.dotfiles/linux/symlinks/{{ item }} dest=~/.{{ item }} state=link
      sudo: no
      with_items:
        - aliases
        - bashrc

    - file: src=~/.dotfiles/symlinks/{{ item }} dest=~/.{{ item }} state=link
      sudo: no
      with_items:
        - bash_prompt
        - nanorc
        - gitconfig
