---
- hosts: all
  gather_facts: yes
  sudo: yes

  pre_tasks:
    - get_url: url=https://deb.nodesource.com/setup dest=/root/add_node_repository.sh
    - command: /bin/bash /root/add_node_repository.sh
    - file: path=/root/add_node_repository.sh state=absent
    - apt: update_cache=yes
    - apt: upgrade=dist

  tasks:
    - apt: name={{ item }} state=present
      with_items:
        - bash-completion
        - nodejs
        - git
        - htop
        - alpine-pico
        - tree
        - watch
        - wget
        - curl
        - autojump
        - mtr
        - multitail

  post_tasks:
    - file: src=~/.dotfiles/linux/symlinks/{{ item }} dest=~/.{{ item }} state=link
      with_items:
        - aliases
        - bashrc

    - file: src=~/.dotfiles/symlinks/{{ item }} dest=~/.{{ item }} state=link
      with_items:
        - bash_prompt
        - functions
        - gitconfig
        - gitignore
        - jshintrc
        - nanorc
        - pylintrc
