---
- hosts: all
  gather_facts: yes
  sudo: yes

  pre_tasks:
    - get_url: url=https://deb.nodesource.com/setup dest=/root/add_node_repository.sh
      when: ansible_distribution == 'Ubuntu'
    - command: /bin/bash /root/add_node_repository.sh
      when: ansible_distribution == 'Ubuntu'

    - file: path=/root/add_node_repository.sh state=absent
      when: ansible_distribution == 'Ubuntu'
    - apt: update_cache=yes
    - apt: upgrade=dist

  tasks:
    - apt: name={{ item }} state=present
      sudo: yes
      with_items:
        - bash-completion
        - nodejs
        - git
        - htop
        - alpine-pico
        - tree
        - watch
        - wget
        - curl
        - autojump
        - mtr
        - multitail

    - name: Remove packages
      apt: name={{ item }} state=absent purge=yes
      with_items:
        - update-notifier-common
        - landscape-common
        - update-manager-core
        - ubuntu-release-upgrader-core
        - update-motd
      when: ansible_distribution == 'Ubuntu'

  post_tasks:
    - file: path=~/.{{ item }} state=absent
      with_items:
        - aliases
        - bashrc
        - bash_prompt
        - nanorc
      sudo: no

    - file: src=~/.dotfiles/linux/symlinks/{{ item }} dest=~/.{{ item }} state=link
      sudo: no
      with_items:
        - aliases
        - bashrc

    - file: src=~/.dotfiles/symlinks/{{ item }} dest=~/.{{ item }} state=link
      sudo: no
      with_items:
        - bash_prompt
        - nanorc
