---
- apt: name=nginx-extras state=present
- file: path=/home/virtual/ state=directory mode=0777 owner=afterdesign group=afterdesign
- file: path=/etc/nginx/sites-enabled/default state=absent
- file: path=/etc/nginx/sites-available/default state=absent
- git: repo=https://github.com/afterdesign/malinowski.be.git dest=/home/virtual/malinowski.be
  sudo: no
- copy: src=malinowski.be dest=/etc/nginx/sites-available/
- file: src=/etc/nginx/sites-available/malinowski.be dest=/etc/nginx/sites-enabled/malinowski.be state=link
  notify:
    - restart nginx
